name: Pull Request Build

on:
  pull_request:
    branches: [ "main" ]

# Cancel currently running workflow for same PR
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_OUTPUT
      id: extract_branch

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install cookiecutter
      run: python3 -m pip install --user cookiecutter

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run cookiecutter
      run: |
        cookiecutter https://github.com/SimformSolutionsPvtLtd/Android_Project_Setup.git \
          --no-input \
          app_name="Simform" \
          repo_name="Simform" \
          package_name="com.simform.app" \
          appcenter_key="" \
          package_dir="com/simform/app" \
          copyright_year_name="2023 Simform" \
          include_testing="n" \
          include_room_db="y" \
          launch_studio="false"
    
    - name: Switch static analysis to this PR's branch
      run: |
        cd Simform/settings
        git switch -c "${{ steps.extract_branch.outputs.branch }}" "origin/${{ steps.extract_branch.outputs.branch }}"
        cd ../..
    
    - name: Run settings setup.sh 
      run: |
        cd Simform/settings
        chmod +x setup.sh
        ./setup.sh
        cd ../..

    - name: Build Project
      run: |
        cd Simform
        chmod +x gradlew
        ./gradlew assembleDevDebug

